[package]
name 		 = "ibc-client-tendermint-cw"
authors 	 = { workspace = true }
edition 	 = { workspace = true }
license 	 = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version 	 = { workspace = true }
keywords     = ["ibc", "light-client", "ics07", "tendermint", "CosmWasm"]
readme       = "./../../README.md"
description  = """
    The CosmWasm contract implementation of the ICS-07 Tendermint light client.
"""

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# ibc dependencies
ibc-core   			  = { workspace = true }
ibc-client-cw         = { workspace = true }
ibc-client-tendermint = { workspace = true }

# cosmwasm dependencies
### Note: Kept at the following version to match the CosmWasm module version
### used by chains supporting the wasm-enabled version of `ibc-go` v7.3
### (This is the min version of `ibc-go` that supports `08-wasm` light clients)
cosmwasm-std 	      = "1.5.2"

[dev-dependencies]
cosmwasm-vm           = "1.5.2"
hex				      = "0.4.2"
ibc-testkit 		  = { workspace = true }
ibc-client-tendermint = { workspace = true }
tendermint 		      = { workspace = true }
tendermint-testgen    = { workspace = true }

[features]
default = ["std"]
std = [
	"ibc-core/std",
	"ibc-client-cw/std",
	"ibc-client-tendermint/std",
]

