[package]
name = "abci-tag-proc-marco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "derive"] }
quote = "1.0"
tendermint = {version = "0.27.0", default-features = false }
proc-macro2 = "1.0.47"
