# Automatically open PRs to update outdated deps
# See https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "crates/ibc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "ci/no-std-check"
    schedule:
      interval: "weekly"
