[workspace]

resolver = "2"

members = [
    "crates/ibc",
]

exclude = [
    "ci/no-std-check",
]

[patch.crates-io]
ibc-proto = { git = "https://github.com/cosmos/ibc-proto-rs.git", branch = "mikhail/tendermint-0.27" }
