[workspace]

resolver = "2"

members = [
    "crates/ibc",
    "crates/ibc-framework",
    "crates/ibc-cosmos",
]

exclude = [
    "ci/no-std-check",
]

[patch.crates-io]
# "Update protos to IBC-Go v5.0.0 and Cosmos SDK v0.46.1"
# [rev](https://github.com/cosmos/ibc-proto-rs/commit/65c050e3a20e3a1ef3c1247788b5013112e207d7)
ibc-proto = { git = "https://github.com/cosmos/ibc-proto-rs", rev = "65c050e3a20e3a1ef3c1247788b5013112e207d7" }
