[workspace]

resolver = "2"

members = [
    "crates/ibc",
]

exclude = [
    "ci/no-std-check",
]

[patch.crates-io]
# We can't use the latest ibc-proto since some fields involved in crossing-hellos are marked deprecated.
# Remove `rev` when we remove crossing hellos.
ibc-proto = { git = "https://github.com/cosmos/ibc-proto-rs", rev = "5f8b99c4b36101722d6ad01803bda4ae9e649bce" }
