[package]
name         = "ibc-core-extra"
version      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
keywords     = ["blockchain", "cosmos", "ibc"]
readme       = "README.md"
description  = """
    TBD
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
# external dependencies
derive_more = { workspace = true }
displaydoc = { workspace = true }
prost = { workspace = true }
subtle-encoding = { workspace = true }

# ibc dependencies
ibc = { workspace = true }
ibc-core-client-types = { workspace = true }
ibc-core-client-context = { workspace = true }
ibc-core-connection-types = { workspace = true }
ibc-core-commitment-types = { workspace = true }
ibc-core-host-types = { workspace = true }
ibc-core-context-types = { workspace = true }
ibc-primitives = { workspace = true }
ibc-proto = { workspace = true }

# cosmos dependencies
tendermint = { workspace = true }

[dev-dependencies]
ibc-testkit = { workspace = true }
[features]
default = ["std"]
std = [
]
serde = [
]