[package]
name         = "ibc-core-client"
version      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
keywords     = ["blockchain", "cosmos", "ibc"]
readme       = "README.md"
description  = """
    Provides the implementation of ICS-02 client, while also re-exporting
    relevant necessary data structures and APIs for seamless integration.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
# external dependencies
prost = { workspace = true }

# ibc dependencies
ibc-core-client-types     = { workspace = true }
ibc-core-client-context   = { workspace = true }
ibc-core-commitment-types = { workspace = true }
ibc-core-host-types       = { workspace = true }
ibc-core-context          = { workspace = true }
ibc-derive                = { workspace = true }
ibc-primitives            = { workspace = true }

[features]
default = ["std"]
std = [
    "prost/std",
    "ibc-core-client-types/std",
    "ibc-core-client-context/std",
    "ibc-core-commitment-types/std",
    "ibc-core-host-types/std",
    "ibc-core-context/std",
    "ibc-primitives/std",
]
serde = [
    "ibc-core-client-types/serde",
    "ibc-core-client-context/serde",
    "ibc-core-commitment-types/serde",
    "ibc-core-host-types/serde",
    "ibc-core-context/serde",
    "ibc-primitives/serde",
]
borsh = [
    "ibc-core-client-types/borsh",
    "ibc-core-client-context/borsh",
    "ibc-core-commitment-types/borsh",
    "ibc-core-host-types/borsh",
    "ibc-core-context/borsh",
    "ibc-primitives/borsh",
]
schema = [
    "ibc-core-client-types/schema",
    "ibc-core-client-context/schema",
    "ibc-core-commitment-types/schema",
    "ibc-core-host-types/schema",
    "ibc-core-context/schema",
    "ibc-primitives/schema",
    "serde",
    "std"
]
parity-scale-codec = [
    "ibc-core-client-types/parity-scale-codec",
    "ibc-core-client-context/parity-scale-codec",
    "ibc-core-commitment-types/parity-scale-codec",
    "ibc-core-context/parity-scale-codec",
    "ibc-core-host-types/parity-scale-codec",
    "ibc-primitives/parity-scale-codec",
]
