[package]
name         = "ibc-testkit"
version      = "0.47.0"
edition      = "2021"
readme       = "README.md"
keywords     = ["blockchain", "consensus", "cosmos", "ibc", "tendermint"]
repository   = "https://github.com/cosmos/ibc-rs"
authors      = ["Informal Systems <hello@informal.systems>"]
rust-version = "1.60"
description  = """
    `ibc-testkit` is a versatile library that provides essential abstractions and implementations, 
    fulfilling a dual role of enabling rigorous integration testing for the `ibc-rs` implementation 
    while also aiding host chains in addressing a broad spectrum of testing scenarios during 
    their integration with `ibc-rs`.
"""

[features]
default = ["std"]
std = [
    "ibc/std",
    "tracing/std",
    "prost/std",
    "serde/std",
    "serde_json/std",
]

# This feature is required for token transfer (ICS-20)
serde = ["dep:serde", "ibc/serde", "serde_json"]

[dependencies]
bytes = { version = "1.2.1", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = ["from", "into", "display", "try_into"] }
displaydoc = { version = "0.2", default-features = false }
ibc = { version = "0.47.0" , path = "../ibc" }
parking_lot = { version = "0.12.1", default-features = false }
prost = { version = "0.12", default-features = false }
serde = { version = "1.0", default-features = false, optional = true }
serde_json = { version = "1", default-features = false, optional = true }
subtle-encoding = { version = "0.5", default-features = false }
tendermint = { version = "0.34", default-features = false }
tendermint-testgen = { version = "0.34", default-features = false }
tracing = { version = "0.1.36", default-features = false }
typed-builder = "0.18.0"
primitive-types = { version = "0.12.0", default-features = false, features = ["serde_no_std"] }


[dev-dependencies]
env_logger = "0.10.0"
rstest = "0.18.1"
tracing-subscriber = { version = "0.3.14", features = ["fmt", "env-filter", "json"]}
test-log = { version = "0.2.10", features = ["trace"] }
