[package]
name         = "ibc-client-tendermint"
version      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
readme       = "README.md"
keywords     = ["blockchain", "consensus", "cosmos", "ibc", "tendermint"]
description  = """
    `ibc-client-tendermint` exports the types, handlers, and contexts for implementing Tendermint light clients.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
# ibc dependencies
ibc = { version = "0.47.0", path = "./../../ibc", default-features = false }
ibc-client-tendermint-types = { version = "0.47.0", path = "./types", default-features = false }
ibc-core-commitment-types = { version = "0.47.0", path = "./../../ibc-core/ics23-commitment/types" }
ibc-core-context = { version = "0.47.0", path = "./../../ibc-core/context" }
ibc-core-client-context = { version = "0.47.0", path = "./../../ibc-core/ics02-client/context" }
ibc-core-client-types = { version = "0.47.0", path = "./../../ibc-core/ics02-client/types" }
ibc-core-context-types = { version = "0.47.0", path = "./../../ibc-core/context/types" }
ibc-core-host-types = { version = "0.47.0", path = "./../../ibc-core/ics24-host/types" }
ibc-primitives = { version = "0.47.0", path = "./../../ibc-primitives" }
ibc-proto = { workspace = true, features = ["server"] }

# cosmos dependencies
tendermint-light-client-verifier = { workspace = true, features = ["rust-crypto"] }

prost = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
test-log = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = ["std"]

std = [
    "ibc-proto/std",
    "prost/std",
]