[package]
name         = "ibc-core-channel"
version      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
keywords     = ["blockchain", "cosmos", "ibc"]
readme       = "./../../README.md"
description  = """
    Provides the implementation of ICS-04 channel, while also re-exporting
    relevant necessary data structures and APIs for seamless integration.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
# external dependencies
prost = { workspace = true }

# ibc dependencies
ibc-core-client           = { workspace = true }
ibc-core-connection       = { workspace = true }
ibc-core-channel-types    = { workspace = true }
ibc-core-commitment-types = { workspace = true }
ibc-core-host-types       = { workspace = true }
ibc-core-context          = { workspace = true }
ibc-core-router           = { workspace = true }
ibc-primitives            = { workspace = true }

[features]
default = ["std"]
std = [
    "ibc-core-client/std",
    "ibc-core-connection/std",
    "ibc-core-channel-types/std",
    "ibc-core-commitment-types/std",
    "ibc-core-host-types/std",
    "ibc-core-context/std",
    "ibc-core-router/std",
    "ibc-primitives/std",
]
serde = [
    "ibc-core-client/serde",
    "ibc-core-connection/serde",
    "ibc-core-channel-types/serde",
    "ibc-core-commitment-types/serde",
    "ibc-core-host-types/serde",
    "ibc-core-context/serde",
    "ibc-core-router/serde",
    "ibc-primitives/serde",
]
schema = [
    "ibc-core-client/schema",
    "ibc-core-connection/schema",
    "ibc-core-channel-types/schema",
    "ibc-core-commitment-types/schema",
    "ibc-core-host-types/schema",
    "ibc-core-context/schema",
    "ibc-core-router/schema",
    "ibc-primitives/schema",
]
borsh = [
    "ibc-core-client/borsh",
    "ibc-core-connection/borsh",
    "ibc-core-channel-types/borsh",
    "ibc-core-commitment-types/borsh",
    "ibc-core-host-types/borsh",
    "ibc-core-context/borsh",
    "ibc-core-router/borsh",
    "ibc-primitives/borsh",
]
parity-scale-codec = [
    "ibc-core-client/parity-scale-codec",
    "ibc-core-connection/parity-scale-codec",
    "ibc-core-channel-types/parity-scale-codec",
    "ibc-core-commitment-types/parity-scale-codec",
    "ibc-core-host-types/parity-scale-codec",
    "ibc-core-context/parity-scale-codec",
    "ibc-core-router/parity-scale-codec",
    "ibc-primitives/parity-scale-codec",
]
