[package]
name         = "ibc-core-channel"
version      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
keywords     = ["blockchain", "cosmos", "ibc"]
readme       = "README.md"
description  = """
    TBD
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
# external dependencies
prost = { workspace = true }

# ibc dependencies
ibc-core-client = { workspace = true }
ibc-core-connection = { workspace = true }
ibc-core-channel-types = { workspace = true }
ibc-core-commitment-types = { workspace = true }
ibc-core-host-types = { workspace = true }
ibc-core-context = { workspace = true }
ibc-core-router = { workspace = true }

[features]
default = ["std"]
std = [
    "ibc-core-client/std",
    "ibc-core-connection/std",
    "ibc-core-channel-types/std",
    "ibc-core-commitment-types/std",
    "ibc-core-host-types/std",
    "ibc-core-context/std",
    "ibc-core-router/std",
]
serde = [
    "ibc-core-client/serde",
    "ibc-core-connection/serde",
    "ibc-core-channel-types/serde",
    "ibc-core-commitment-types/serde",
    "ibc-core-host-types/serde",
    "ibc-core-context/serde",
    "ibc-core-router/serde",
]