[package]
name = "ibc-client-wasm-types"
version      = { workspace = true }
authors      = { workspace = true }
license      = { workspace = true }
rust-version = { workspace = true }
edition      = { workspace = true }

[dependencies]
# external dependencies
base64          = { workspace = true, features = ["alloc"] }
displaydoc      = { workspace = true }
serde           = { workspace = true , optional = true }
cosmwasm-schema = { version = "1.4.1", default-features = false, optional = true }

# ibc dependencies
ibc-core-client     = { workspace = true }
ibc-core-host-types = { workspace = true }
ibc-primitives      = { workspace = true }
ibc-proto           = { workspace = true }

[dev-dependencies]
rstest     = { workspace = true }
serde_json = { workspace = true }

[features]
default = ["std"]
std = [
	"ibc-core-client/std",
	"ibc-core-host-types/std",
	"ibc-proto/std",
	"base64/std",
	"serde/std"
]
serde = [
	"ibc-core-client/serde",
	"ibc-core-host-types/serde",
	"ibc-primitives/serde",
	"ibc-proto/serde",
	"dep:serde"
]
schema = [
	"ibc-core-client/schema",
	"ibc-core-host-types/schema",
	"ibc-primitives/schema",
	"ibc-proto/json-schema",
	"serde",
	"std"
]
cosmwasm = [
	"cosmwasm-schema",
	"schema"
]
