[package]
name         = "ibc-app-transfer"
version      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
keywords     = ["blockchain", "cosmos", "ibc", "transfer", "ics20"]
readme       = "./../README.md"
description  = """
    Contains the core implementation of the ICS-20 token transfer application logic
    along with re-exporting the data structures from `ibc-app-transfer-types` crate.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
# external dependencies
serde_json =  { workspace = true, optional = true }
sha2 = { workspace = true }

# ibc dependencies
ibc = { workspace = true }
ibc-app-transfer-types = { workspace = true }

[dev-dependencies]
subtle-encoding = { workspace = true }

[features]
default = ["std"]
std = [
    "ibc-app-transfer-types/std",
    "ibc/std",
    "serde_json/std",
    "sha2/std",
]
serde = [
    "ibc-app-transfer-types/serde",
    "ibc/serde",
    "serde_json"
]
schema = [
    "ibc-app-transfer-types/schema",
    "ibc/schema",
    "serde",
    "std",
]
borsh = [
    "ibc-app-transfer-types/borsh",
    "ibc/borsh",
]
parity-scale-codec = [
    "ibc-app-transfer-types/parity-scale-codec",
    "ibc/parity-scale-codec",
]
