[package]
name         = "ibc-core-connection"
version      = { workspace = true }
authors      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
keywords     = ["blockchain", "cosmos", "ibc"]
readme       = "./../README.md"
description  = """
    Provides the implementation of ICS-03 connection, while also re-exporting
    relevant necessary data structures and APIs for seamless integration.
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
# external dependencies
prost = { workspace = true }

# ibc dependencies
ibc-core-client           = { workspace = true }
ibc-core-connection-types = { workspace = true }
ibc-core-host-types       = { workspace = true }
ibc-core-context          = { workspace = true }
ibc-primitives            = { workspace = true }

[features]
default = ["std"]
std = [
    "ibc-core-client/std",
    "ibc-core-connection-types/std",
    "ibc-core-host-types/std",
    "ibc-core-context/std",
    "ibc-primitives/std",
]
serde = [
    "ibc-core-client/serde",
    "ibc-core-connection-types/serde",
    "ibc-core-host-types/serde",
    "ibc-core-context/serde",
    "ibc-primitives/serde",
]
schema = [
    "ibc-core-client/schema",
    "ibc-core-connection-types/schema",
    "ibc-core-host-types/schema",
    "ibc-primitives/schema",
    "serde",
    "std"
]
borsh = [
    "ibc-core-client/borsh",
    "ibc-core-host-types/borsh",
    "ibc-core-context/borsh",
    "ibc-primitives/borsh",
]
parity-scale-codec = [
    "ibc-core-client/parity-scale-codec",
    "ibc-core-host-types/parity-scale-codec",
    "ibc-primitives/parity-scale-codec",
]