name: Code Quality Checks
on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    env:
      RIPGREP_VERSION: 14.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Ripgrep
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: BurntSushi/ripgrep
          version: "tags/${{ env.RIPGREP_VERSION }}"
          file: "ripgrep-${{ env.RIPGREP_VERSION }}-x86_64-unknown-linux-musl.tar.gz"

      - name: Create local bin directory
        run: |
          mkdir -p ~/local/bin
          echo "${HOME}/local/bin" >> $GITHUB_PATH

      - name: Setup ripgrep
        run: |
          tar -xzf "ripgrep-${{ env.RIPGREP_VERSION }}-x86_64-unknown-linux-musl.tar.gz"
          mv "ripgrep-${{ env.RIPGREP_VERSION }}-x86_64-unknown-linux-musl/rg" rg
          chmod +x rg
          mv rg ~/local/bin
          rm -r "ripgrep-${{ env.RIPGREP_VERSION }}-x86_64-unknown-linux-musl"

      - name: Check for tabs
        run: |
          ! rg '\t'

      - name: Check for trailing whitespace
        run: |
          ! rg '\s+$'

      - name: Spell Check with Typos
        uses: crate-ci/typos@master
        with:
          config: ./.github/typos.toml
