name: Code Quality Checks
on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    env:
      RIPGREP_VERSION: 14.1.0
      FD_VERSION: 9.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Whitestapace lints
        run: bash ci/code-quality/whitespace-lints.sh

      - name: Spell Check with Typos
        uses: crate-ci/typos@v1.19.0 # NOTE: Newer versions detect false positives. Test locally before upgrading.
        with:
          config: ./.github/typos.toml
