name: CosmWasm Compilation Check
on:
  pull_request:
    paths:
      - .github/workflows/cw-check.yaml
      - Cargo.toml
      - Cargo.lock
      - ci/cw-check/**
  push:
    tags:
      - v[0-9]+.*
    branches:
      - "release/*"
      - main
    paths:
      - .github/workflows/cw-check.yaml
      - Cargo.toml
      - Cargo.lock
      - ci/cw-check/**
      - ci/**
      - ibc/**
      - ibc-core/**
      - ibc-apps/**
      - ibc-data-types/**
      - ibc-clients/**
      - ibc-primitives/**
      - ibc-derive/**
  merge_group:
    types: [checks_requested]

jobs:
  cw-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      # only for caching cargo build artifacts from `cosmwasm/optimizer`
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Compile `cw-check`
        run: |
          docker run --rm -v "$(pwd)":/code \
          --mount type=volume,source="cw_check_cache",target=/code/ci/cw-check/target \
          --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
          cosmwasm/optimizer:0.15.0 ./ci/cw-check

      - name: Install `cosmwasm-check` from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cosmwasm-check

      - name: Check compiled CosmWasm contract
        run: cosmwasm-check artifacts/cw_check.wasm
