name: CosmWasm Compilation Check
on:
  pull_request:
    paths:
      - .github/workflows/cw-check.yml
      - ci/cw-check/**
  push:
    tags:
      - v[0-9]+.*
    branches:
      - "release/*"
      - main
    paths:
      - .github/workflows/cw-check.yml
      - Cargo.toml
      - Cargo.lock
      - ci/cw-check/**
      - ci/**
      - ibc/**
      - ibc-core/**
      - ibc-apps/**
      - ibc-data-types/**
      - ibc-clients/**
      - ibc-primitives/**
      - ibc-query/**
      - ibc-derive/**
jobs:
  cw-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          is_ci: true
      - name: Run cw-check
        run: |
          cd ci/cw-check
          nix-shell --run "cw-check"
