name: CosmWasm Compilation Check
on:
  pull_request:
    paths:
      - .github/workflows/cw-check.yml
      - Cargo.toml
      - Cargo.lock
      - ci/cw-check/**
      - ci/**
      - ibc/**
      - ibc-core/**
      - ibc-apps/**
      - ibc-data-types/**
      - ibc-clients/**
      - ibc-primitives/**
      - ibc-derive/**
  push:
    tags:
      - v[0-9]+.*
    branches:
      - "release/*"
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main' }}

jobs:
  cw-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      # only for caching cargo build artifacts from `cosmwasm/optimizer`
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Compile `cw-check`
        run: |
          docker run \
          -v "$(pwd)":/code \
          -v "${HOME}/.cargo/registry":/usr/local/cargo/registry \
          cosmwasm/optimizer:0.15.1 ./ci/cw-check

      - name: Install `cosmwasm-check` from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cosmwasm-check

      - name: Check compiled CosmWasm contract
        run: cosmwasm-check artifacts/cw_check.wasm
