name: CosmWasm Compilation Check
on:
  pull_request:
    paths:
      - .github/workflows/cw-check.yml
      - Cargo.toml
      - Cargo.lock
      - ci/**
      - crates/**
  push:
    branches: main
    paths:
      - .github/workflows/cw-check.yml
      - Cargo.toml
      - Cargo.lock
      - ci/**
      - crates/**

jobs:
  cw-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Use cachix cache
        uses: cachix/cachix-action@v12
        with:
          name: ibc

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run cw-check
        run: |
          cd ci/cw-check
          nix-shell shell.nix --command "cw-check"